version: '3.1'

services:
  app:
    container_name: gobayarind
    build:
      context: .
      dockerfile: Dockerfile
    command: ["go", "run", "main.go"]
    environment:
      - JWT_SECRET=0daf08301d31b170af6e43979d13efbdede03ce5388bde66057358d897545fde
      - SECRET_KEY=awokoakoko21kokwaokd2k1ookawok412koakkwako412okaokfenjnoj12ijiwd
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=admin1234
      - DB_NAME=gobayarind
    networks:
      - app-network
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db

  postgres_db:
    container_name: postgres_db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=gobayarind
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
